name: Gitflow Release

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist_credentials: false 

      - uses: fregante/setup-git-token@v1
        name: Setting up GitHub credentials
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          name: Release-Bot
          email: releases@riverigaming.com
        
      - name: Checkout master/develop/release branch
        run: |
          git checkout master
          git checkout develop
          git checkout "${{ github.head_ref }}"
      - name: Setting up environment
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setting up maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v7
        with:
          servers: '[{ "id": "river-nexus", "username": "${{ secrets.NEXUS_USERNAME }}", "password": "${{ secrets.NEXUS_PASSWORD }}" }]'
          mirrors: '[{ "id": "river-nexus", "mirrorOf": "*", "url": "https://nexus.riverigaming.tech/repository/maven-public/" }]'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ! ~/.m2/repository/com/river
            ! ~/.m2/repository/com/bejig
          key: river-cache
          restore-keys: river-cache

      - name: Extracting release version
        run: |
          echo ${{ github.head_ref }} | grep -oP "(?<=^release\/)(([0-9]+.){2,3}[0-9]+)$"
          export VERSION=$(echo ${{ github.head_ref }} | grep -oP "(?<=^release\/)(([0-9]+.){2,3}[0-9]+)$")
          echo Setting version to [$VERSION]
          echo ::set-env name=VERSION::$(echo "$VERSION")
      - name: Setting release version
        run: |
          mvn versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false -ntp
          git commit -am "Updating version to ${{ env.VERSION }}"

      - name: Finishing release
        run: |
          git checkout master
          git merge release/1.3.0
          git push origin master
